Repository EreliaCorp/Sparkle, pull requests merged in 2023-07, with the labels that each got.

#164 Add job names to PersistantWorker and Application
  includes/application/concrete/linux/spk_graphical_application.hpp
  includes/application/concrete/windows/spk_graphical_application.hpp
  includes/application/spk_abstract_application.hpp
  includes/iostream/spk_iostream.hpp
  includes/miscellaneous/spk_translation_atlas.hpp
  includes/spk_basic_functions.hpp
  includes/threading/spk_persistent_worker.hpp
  playground/src/main.cpp
  src/application/spk_abstract_application.cpp
  src/spk_basic_functions.cpp
  src/threading/spk_persistent_worker.cpp
Labels: New feature

#168 Leaks fix.
  includes/graphics/linux/spk_window.hpp
  includes/iostream/spk_iostream.hpp
  src/graphics/linux/spk_window.cpp
Labels: Edition

#166 Network implementation
  CMakeLists.txt
  includes/application/concrete/linux/spk_graphical_application.hpp
  includes/data_structure/spk_data_buffer.hpp
  includes/graphics/spk_window.hpp
  includes/iostream/spk_iostream.hpp
  includes/miscellaneous/spk_translation_atlas.hpp
  includes/network/linux/spk_acceptor.hpp
  includes/network/linux/spk_socket.hpp
  includes/network/spk_acceptor.hpp
  includes/network/spk_central_node.hpp
  includes/network/spk_client.hpp
  includes/network/spk_local_node.hpp
  includes/network/spk_message.hpp
  includes/network/spk_network_object.hpp
  includes/network/spk_node.hpp
  includes/network/spk_remote_node.hpp
  includes/network/spk_server.hpp
  includes/network/spk_socket.hpp
  includes/network/windows/spk_acceptor.hpp
  includes/network/windows/spk_network_object.hpp
  includes/network/windows/spk_socket.hpp
  includes/sparkle.hpp
  includes/spk_basic_functions.hpp
  includes/spk_system_define.hpp
  includes/threading/spk_thread_safe_queue.hpp
  includes/widget/spk_abstract_widget.hpp
  includes/widget/spk_central_node_manager.hpp
  includes/widget/spk_client_manager.hpp
  includes/widget/spk_remote_node_manager.hpp
  includes/widget/spk_server_manager.hpp
  playground/src/en_EN.json
  playground/src/main.cpp
  src/application/modules/spk_widget_module.cpp
  src/application/spk_abstract_application.cpp
  src/basic_functions/linux/spk_basic_functions.cpp
  src/basic_functions/spk_basic_functions.cpp
  src/basic_functions/windows/spk_basic_functions.cpp
  src/data_structure/spk_data_buffer.cpp
  src/network/linux/spk_acceptor.cpp
  src/network/linux/spk_socket.cpp
  src/network/spk_central_node.cpp
  src/network/spk_client.cpp
  src/network/spk_local_node.cpp
  src/network/spk_message.cpp
  src/network/spk_node.cpp
  src/network/spk_remote_node.cpp
  src/network/spk_server.cpp
  src/network/windows/spk_acceptor.cpp
  src/network/windows/spk_network_object.cpp
  src/network/windows/spk_socket.cpp
  src/threading/spk_persistent_worker.cpp
  src/widget/spk_central_node_manager.cpp
  src/widget/spk_client_manager.cpp
  src/widget/spk_remote_node_manager.cpp
  src/widget/spk_server_manager.cpp
Labels: Creation

#177 Fix compilation errors.
  includes/application/spk_application.hpp
  includes/widget/spk_widget_interface.hpp
  src/graphics/linux/spk_window.cpp
  src/network/linux/spk_network_acceptor.cpp
Labels: Bug
